-- 8 West IT RMM — MySQL schema (HostGator / cPanel compatible: MySQL 5.7+ / MariaDB)
-- Create the database in cPanel first, then import this file via phpMyAdmin.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- --------------------------------------------------------
-- Portal users (you and any techs who log into the dashboard)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username      VARCHAR(64)  NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name     VARCHAR(128) NOT NULL DEFAULT '',
  role          ENUM('admin','tech') NOT NULL DEFAULT 'admin',
  is_active     TINYINT(1)   NOT NULL DEFAULT 1,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at DATETIME     NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Clients (the businesses you support)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS clients (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name        VARCHAR(128) NOT NULL,
  notes       TEXT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_clients_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Enrollment keys — pre-shared secrets baked into an agent MSI.
-- An agent presents this once to enroll and receives its own token.
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS enrollment_keys (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  client_id   INT UNSIGNED NULL,
  label       VARCHAR(128) NOT NULL DEFAULT '',
  key_value   CHAR(64) NOT NULL,           -- random hex, given to the installer
  is_active   TINYINT(1) NOT NULL DEFAULT 1,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_enroll_key (key_value),
  KEY idx_enroll_client (client_id),
  CONSTRAINT fk_enroll_client FOREIGN KEY (client_id)
    REFERENCES clients(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Agents (one row per enrolled computer)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS agents (
  id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
  client_id       INT UNSIGNED NULL,
  agent_uid       CHAR(36) NOT NULL,        -- GUID generated by the agent at install
  auth_token_hash CHAR(64) NOT NULL,        -- sha256 of the bearer token we issued
  hostname        VARCHAR(128) NOT NULL DEFAULT '',
  display_name    VARCHAR(128) NOT NULL DEFAULT '',
  os_name         VARCHAR(128) NOT NULL DEFAULT '',
  os_version      VARCHAR(64)  NOT NULL DEFAULT '',
  last_user       VARCHAR(128) NOT NULL DEFAULT '',
  public_ip       VARCHAR(45)  NOT NULL DEFAULT '',
  local_ip        VARCHAR(45)  NOT NULL DEFAULT '',
  agent_version   VARCHAR(32)  NOT NULL DEFAULT '',
  rustdesk_id     VARCHAR(32)  NOT NULL DEFAULT '',  -- reported by agent for remote-in
  rustdesk_pass   VARCHAR(128) NOT NULL DEFAULT '',  -- permanent unattended password
  enrolled_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at    DATETIME NULL,
  heartbeat_secs  INT UNSIGNED NOT NULL DEFAULT 60,
  is_archived     TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_agents_uid (agent_uid),
  KEY idx_agents_client (client_id),
  KEY idx_agents_lastseen (last_seen_at),
  CONSTRAINT fk_agents_client FOREIGN KEY (client_id)
    REFERENCES clients(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Hardware/software inventory snapshots (latest JSON blob per agent)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory (
  agent_id    INT UNSIGNED NOT NULL,
  data_json   MEDIUMTEXT NOT NULL,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (agent_id),
  CONSTRAINT fk_inv_agent FOREIGN KEY (agent_id)
    REFERENCES agents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Jobs (commands queued for an agent to run; agent polls and reports back)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS jobs (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  agent_id     INT UNSIGNED NOT NULL,
  created_by   INT UNSIGNED NULL,
  job_type     ENUM('powershell','cmd','restart','message','rustdesk_refresh') NOT NULL DEFAULT 'powershell',
  payload      MEDIUMTEXT NOT NULL DEFAULT '',
  status       ENUM('queued','running','done','error','expired') NOT NULL DEFAULT 'queued',
  exit_code    INT NULL,
  output       MEDIUMTEXT NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  picked_at    DATETIME NULL,
  finished_at  DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_jobs_agent_status (agent_id, status),
  CONSTRAINT fk_jobs_agent FOREIGN KEY (agent_id)
    REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_jobs_user FOREIGN KEY (created_by)
    REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Audit log (who did what)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id    INT UNSIGNED NULL,
  agent_id   INT UNSIGNED NULL,
  action     VARCHAR(64) NOT NULL,
  detail     VARCHAR(512) NOT NULL DEFAULT '',
  ip         VARCHAR(45) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_audit_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
